include:
  - project: 'turris/c-template'
    ref: base
    file: '/base-ci.yml'


# Disable tests execution on Alpine
# Musl declares stderr as constant and thus we are unable to replace it to test
# default output.
build:alpine:
  script:
    - meson setup -Dtests=disabled build
    - meson compile -C build
test:alpine:
  script:
    - echo "Tests are not supported on Musl"
valgrind:memcheck:alpine:
  script:
    - echo "Tests are not supported on Musl"
valgrind:drd:alpine:
  script:
    - echo "Tests are not supported on Musl"
